name: Run Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: use NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Lint project
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    services:
      postgres:
        image: postgres:11-alpine
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: casbin
          POSTGRES_PASSWORD: casbin
          POSTGRES_DB: casbin

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test:ci
      env:
        CI: true

    - name: Collect coverage
      uses: coverallsapp/github-action@master
      if: matrix.node-version == '12.x'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
